### ISSUE TITLE
Не удаляются линии по диагоналям

### ISSUE THREAD

**Issue by nonamenix** [iliyat/wargaming-test-lines#2]
<img width="443" alt="2015-07-24 20 27 35" src="https://cloud.githubusercontent.com/assets/634394/8880631/e5daec2e-3242-11e5-9841-165e3ce40496.png">

**Comment by iliyat** [comment]
@nonamenix Да, сейчас проверка только по горизонтали и вертикали. По аналогии с принципом перемещения из описания - "...состоит из одного или нескольких перемещений шара на одну клетку по вертикали или горизонтали, но не диагонали".
